import { AppProps } from 'next/app';
import Head from 'next/head';
import { MantineProvider } from '@mantine/core';

// 1. import `NextUIProvider` component
import { NextUIProvider } from '@nextui-org/react';

export default function App(props: AppProps) {
  const { Component, pageProps } = props;

  return (
    <NextUIProvider>
      <Head>
        <title>Wiki Realms</title>
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MantineProvider
        withGlobalStyles
        withNormalizeCSS
        theme={{
          /** Put your mantine theme override here */
          colorScheme: 'light',
        }}
      >
        <Component {...pageProps} />
      </MantineProvider>
    </NextUIProvider>
  );
}