import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
// import { Button } from '@mantine/core'
import { Grid, Card, Text } from "@nextui-org/react";
import { Button } from "@nextui-org/react";
import { useMediaQuery } from './useMediaQuery.js'
import { RealmCard } from '../components/RealmCard.js'
import { MantineRealmCard } from "../components/MantineRealmCard.js"



const inter = Inter({ subsets: ['latin'] })

export default function Home()
{

  const isMd = useMediaQuery(960);

  const MockItem = ({ text }: { text: string }) => {
    return (
      <Card css={{ h: "$24", $$cardColor: '$colors$primary' }}>
        <Card.Body>
          <Text h6 size={15} color="white" css={{ mt: 0 }}>
            {text}
          </Text>
        </Card.Body>
      </Card>
    );
  };



  return (
    <>
      <Head>
        <title>Wiki Realms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.center}>
          <Text h1 color="secondary">Wiki Realms</Text>
        </div>

        {/* <div className={styles.center}>
          <Button color="secondary" ghost auto>Hello there!</Button>
        </div> */}

        <Grid.Container gap={4} justify="center">

          <Grid xs={12} md={10} lg={8} >
            <RealmCard title="Aeyrelia" imageUrl="/img/A_New_Beginning.jpeg" />
          </Grid>

          <Grid xs={12} md={10} lg={8} >
            <RealmCard title="Akila" imageUrl="https://i.pinimg.com/564x/48/05/1c/48051c35ae67e0425e205a3ad8d2127c.jpg" />
          </Grid>

          <Grid xs={12} md={10} lg={8} >
            <MantineRealmCard />
          </Grid>

        </Grid.Container>

      </main>
    </>
  );
}
